import RequestProject.GeneralSignaling

/-!
# Finite Bayesian game infrastructure

This file formalizes the game-theoretic layer of Section 2.  A finite environment has a
prior over world models, world-dependent training observations, and a fresh
world-dependent draw of the label and two inference signals.  Contract-indexed
information types then state exactly what each firm observes.  The remainder of the file
provides pure and mixed strategies, expected and interim utility, Bayesian best responses,
equilibrium, Pareto dominance, individual rationality, and IRPO.

The finite presentation is intended as an exact discrete counterpart of the paper's
measurable model, while keeping all expectations explicit and computational.
-/

namespace TrainSharing

/-- The two firms. -/
inductive Firm where
  | firm1
  | firm2
  deriving DecidableEq, Fintype, Repr

/-- The other firm. -/
def Firm.other : Firm → Firm
  | .firm1 => .firm2
  | .firm2 => .firm1

@[simp] theorem Firm.other_other (i : Firm) : i.other.other = i := by
  cases i <;> rfl

/-- A complete inference-stage realization: true label, Firm 1's signal, Firm 2's signal. -/
abbrev InferenceOutcome := Bool × Bool × Bool

/-- A finite version of the paper's Bayesian environment.

Training observations and the fresh inference example are conditionally independent given
`world`; arbitrary dependence between the firms' observations is retained inside each
world-dependent joint law. -/
structure BayesianEnvironment
    (World Train1 Train2 : Type)
    [Fintype World] [Fintype Train1] [Fintype Train2] where
  prior : FiniteLaw World
  training : World → FiniteLaw (Train1 × Train2)
  inference : World → FiniteLaw InferenceOutcome

variable {World Train1 Train2 : Type}
  [Fintype World] [Fintype Train1] [Fintype Train2]

namespace BayesianEnvironment

/-- Joint mass of a complete realization generated by the environment. -/
def completeMass (E : BayesianEnvironment World Train1 Train2)
    (w : World) (z : Train1 × Train2) (o : InferenceOutcome) : ℝ :=
  E.prior.mass w * (E.training w).mass z * (E.inference w).mass o

/-- Marginal probability of a pair of training observations. -/
def trainingPairMass (E : BayesianEnvironment World Train1 Train2)
    (z : Train1 × Train2) : ℝ :=
  ∑ w, E.prior.mass w * (E.training w).mass z

/-- Marginal probability of one firm's training observation. -/
def trainingMass (E : BayesianEnvironment World Train1 Train2) :
    (i : Firm) → (if i = .firm1 then Train1 else Train2) → ℝ
  | .firm1, t1 => ∑ w, E.prior.mass w * ∑ t2, (E.training w).mass (t1, t2)
  | .firm2, t2 => ∑ w, E.prior.mass w * ∑ t1, (E.training w).mass (t1, t2)

/-- Posterior probability of a world after one firm's training observation.
It is defined as zero when the observation has zero prior probability. -/
noncomputable def posteriorWorld (E : BayesianEnvironment World Train1 Train2) :
    (i : Firm) → (if i = .firm1 then Train1 else Train2) → World → ℝ
  | .firm1, t1, w =>
      (E.prior.mass w * ∑ t2, (E.training w).mass (t1, t2)) /
        E.trainingMass .firm1 t1
  | .firm2, t2, w =>
      (E.prior.mass w * ∑ t1, (E.training w).mass (t1, t2)) /
        E.trainingMass .firm2 t2

lemma completeMass_nonneg (E : BayesianEnvironment World Train1 Train2)
    (w : World) (z : Train1 × Train2) (o : InferenceOutcome) :
    0 ≤ E.completeMass w z o := by
  simp [completeMass]
  exact mul_nonneg (mul_nonneg (E.prior.nonneg w) ((E.training w).nonneg z))
    ((E.inference w).nonneg o)

lemma completeMass_total (E : BayesianEnvironment World Train1 Train2) :
    ∑ w, ∑ z, ∑ o, E.completeMass w z o = 1 := by
  simp_rw [completeMass, ← Finset.mul_sum, (E.inference _).total, mul_one]
  simp_rw [← Finset.mul_sum, (E.training _).total, mul_one]
  exact E.prior.total

lemma posteriorWorld_total_firm1 (E : BayesianEnvironment World Train1 Train2)
    (t1 : Train1) (hpos : 0 < E.trainingMass .firm1 t1) :
    ∑ w, E.posteriorWorld .firm1 t1 w = 1 := by
  simp only [posteriorWorld]
  rw [← Finset.sum_div]
  rw [div_eq_one_iff_eq (ne_of_gt hpos)]
  simp [trainingMass]

lemma posteriorWorld_total_firm2 (E : BayesianEnvironment World Train1 Train2)
    (t2 : Train2) (hpos : 0 < E.trainingMass .firm2 t2) :
    ∑ w, E.posteriorWorld .firm2 t2 w = 1 := by
  simp [posteriorWorld, trainingMass]
  rw [← Finset.sum_div]
  refine div_self ?_
  simp only [trainingMass] at hpos
  have hpos' : ∑ i, E.prior.mass i * ∑ t1, (E.training i).mass (t1, t2) ≠ 0 := ne_of_gt hpos
  convert hpos'

end BayesianEnvironment

/-- Everything a firm observes when it chooses its action, indexed by contract. -/
def Information (Train1 Train2 : Type) : Firm → Contract → Type
  | .firm1, .noSharing => Train1 × Bool
  | .firm2, .noSharing => Train2 × Bool
  | .firm1, .trainSharing => Train1 × Train2 × Bool
  | .firm2, .trainSharing => Train1 × Train2 × Bool
  | .firm1, .inferSharing => Train1 × Bool × Bool
  | .firm2, .inferSharing => Train2 × Bool × Bool
  | .firm1, .fullSharing => Train1 × Train2 × Bool × Bool
  | .firm2, .fullSharing => Train1 × Train2 × Bool × Bool

/-- Extract a firm's contract-dependent information from a complete realization. -/
def observe (i : Firm) (c : Contract) (z : Train1 × Train2)
    (o : InferenceOutcome) : Information Train1 Train2 i c :=
  match i, c with
  | .firm1, .noSharing => (z.1, o.2.1)
  | .firm2, .noSharing => (z.2, o.2.2)
  | .firm1, .trainSharing => (z.1, z.2, o.2.1)
  | .firm2, .trainSharing => (z.1, z.2, o.2.2)
  | .firm1, .inferSharing => (z.1, o.2.1, o.2.2)
  | .firm2, .inferSharing => (z.2, o.2.1, o.2.2)
  | .firm1, .fullSharing => (z.1, z.2, o.2.1, o.2.2)
  | .firm2, .fullSharing => (z.1, z.2, o.2.1, o.2.2)

/-- A pure action-stage strategy. -/
abbrev PureStrategy (Train1 Train2 : Type) (i : Firm) (c : Contract) :=
  Information Train1 Train2 i c → Bool

/-- A behavioral (mixed) action-stage strategy. -/
abbrev MixedStrategy (Train1 Train2 : Type) [Fintype Train1] [Fintype Train2]
    (i : Firm) (c : Contract) :=
  Information Train1 Train2 i c → FiniteLaw Bool

/-- A pair of pure strategies under one contract. -/
structure PureProfile (Train1 Train2 : Type) (c : Contract) where
  firm1 : PureStrategy Train1 Train2 .firm1 c
  firm2 : PureStrategy Train1 Train2 .firm2 c

/-- A pair of mixed strategies under one contract. -/
structure MixedProfile (Train1 Train2 : Type) [Fintype Train1] [Fintype Train2]
    (c : Contract) where
  firm1 : MixedStrategy Train1 Train2 .firm1 c
  firm2 : MixedStrategy Train1 Train2 .firm2 c

/-- Lift a pure strategy to a degenerate mixed strategy. -/
def PureStrategy.toMixed (s : PureStrategy Train1 Train2 i c) :
    MixedStrategy Train1 Train2 i c := fun info =>
  { mass := fun a => if a = s info then 1 else 0
    nonneg := by intro a; split <;> norm_num
    total := by simp }

/-- Lift a pure profile to a degenerate mixed profile. -/
def PureProfile.toMixed (s : PureProfile Train1 Train2 c) :
    MixedProfile Train1 Train2 c where
  firm1 := s.firm1.toMixed
  firm2 := s.firm2.toMixed

/-- Ex-post utility.  Its arguments are own action, true label, and rival action. -/
abbrev ExPostUtility := Bool → Bool → Bool → ℝ

/-- Utility functions for both firms. -/
def UtilityFamily := Firm → ExPostUtility

/-- The paper's utility generated by its four reward/cost parameters.  If both firms take
an action, each receives half the corresponding exclusive reward or cost. -/
noncomputable def UtilityParameters.exPost (u : UtilityParameters) : ExPostUtility :=
  fun own label rival =>
    let exclusive := if own = label
      then if own then u.reward1 else u.reward0
      else -(if own then u.cost1 else u.cost0)
    if own = rival then exclusive / 2 else exclusive

/-- Both firms have the same ex-post utility function, as assumed in Equation (2). -/
noncomputable def UtilityParameters.family (u : UtilityParameters) : UtilityFamily := fun _ => u.exPost

/-- Probability assigned to an action by the selected mixed strategy. -/
def MixedProfile.actionMass (s : MixedProfile Train1 Train2 c) (i : Firm)
    (z : Train1 × Train2) (o : InferenceOutcome) (a : Bool) : ℝ :=
  match i with
  | .firm1 => (s.firm1 (observe .firm1 c z o)).mass a
  | .firm2 => (s.firm2 (observe .firm2 c z o)).mass a

/-- Ex-ante expected utility under a contract and mixed strategy profile. -/
noncomputable def expectedUtility
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) (s : MixedProfile Train1 Train2 c) (i : Firm) : ℝ :=
  ∑ w, ∑ z, ∑ o, ∑ a1, ∑ a2,
    E.completeMass w z o * s.actionMass .firm1 z o a1 *
      s.actionMass .firm2 z o a2 *
      match i with
      | .firm1 => u .firm1 a1 o.1 a2
      | .firm2 => u .firm2 a2 o.1 a1

open Classical in
/-- Unnormalized interim utility conditional on a specified own training observation.
The omitted positive normalizing constant does not affect best-response comparisons. -/
noncomputable def interimUtility
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) (s : MixedProfile Train1 Train2 c) :
    (i : Firm) → (if i = .firm1 then Train1 else Train2) → ℝ
  | .firm1, t1 =>
      ∑ w, ∑ z, ∑ o, ∑ a1, ∑ a2,
        (if z.1 = t1 then E.completeMass w z o else 0) *
          s.actionMass .firm1 z o a1 * s.actionMass .firm2 z o a2 *
          u .firm1 a1 o.1 a2
  | .firm2, t2 =>
      ∑ w, ∑ z, ∑ o, ∑ a1, ∑ a2,
        (if z.2 = t2 then E.completeMass w z o else 0) *
          s.actionMass .firm1 z o a1 * s.actionMass .firm2 z o a2 *
          u .firm2 a2 o.1 a1

/-- Replace one component of a profile by a unilateral deviation. -/
def MixedProfile.deviate (s : MixedProfile Train1 Train2 c) (i : Firm)
    (d : MixedStrategy Train1 Train2 i c) : MixedProfile Train1 Train2 c :=
  match i with
  | .firm1 => { firm1 := d, firm2 := s.firm2 }
  | .firm2 => { firm1 := s.firm1, firm2 := d }

/-- Ex-ante Bayesian best response. -/
def IsBestResponse
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) (s : MixedProfile Train1 Train2 c) (i : Firm) : Prop :=
  ∀ d : MixedStrategy Train1 Train2 i c,
    expectedUtility E u c s i ≥ expectedUtility E u c (s.deviate i d) i

/-- Bayesian Nash equilibrium under a contract. -/
def IsBayesNash
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) (s : MixedProfile Train1 Train2 c) : Prop :=
  IsBestResponse E u c s .firm1 ∧ IsBestResponse E u c s .firm2

/-- Pure Bayesian Nash equilibrium, via the canonical embedding into mixed strategies. -/
def IsPureBayesNash
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) (s : PureProfile Train1 Train2 c) : Prop :=
  IsBayesNash E u c s.toMixed

/-- Pareto dominance at a realized pair of training observations.  Each firm evaluates
its payoff using its own interim belief, as in Equation (6). -/
def ParetoDominatesAt
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c d : Contract) (z : Train1 × Train2) : Prop :=
  ∃ s : MixedProfile Train1 Train2 c, IsBayesNash E u c s ∧
    ∀ s' : MixedProfile Train1 Train2 d, IsBayesNash E u d s' →
      interimUtility E u c s .firm1 z.1 ≥ interimUtility E u d s' .firm1 z.1 ∧
      interimUtility E u c s .firm2 z.2 ≥ interimUtility E u d s' .firm2 z.2

/-- Contract `c` Pareto dominates `d` if it does so at every possible pair of training
observations, matching the paper's global dominance relation. -/
def ParetoDominates
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c d : Contract) : Prop :=
  ∀ z, 0 < E.trainingPairMass z → ParetoDominatesAt E u c d z

/-- Strict contract dominance in the paper's order-theoretic sense. -/
def StrictlyParetoDominates
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c d : Contract) : Prop :=
  ParetoDominates E u c d ∧ ¬ ParetoDominates E u d c

/-- Individual rationality relative to the default no-sharing contract. -/
def IsIndividuallyRational
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) : Prop :=
  c = .noSharing ∨ ParetoDominates E u c .noSharing

/-- A contract is Pareto optimal if no other contract strictly dominates it. -/
def IsParetoOptimal
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) : Prop :=
  ∀ d, ¬ StrictlyParetoDominates E u d c

/-- Pareto-optimal individual rationality (IRPO). -/
def IsIRPO
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) : Prop :=
  IsIndividuallyRational E u c ∧ IsParetoOptimal E u c

/-- A uniquely IRPO contract. -/
def IsUniquelyIRPO
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c : Contract) : Prop :=
  IsIRPO E u c ∧ ∀ d, IsIRPO E u d → d = c

/-- Literal unique IRPO excludes every distinct contract from being IRPO.  This is the
order-theoretic point used in Theorems 4.3 and 4.5: unlike “unique up to equivalence,”
literal uniqueness does not permit another payoff-equivalent IRPO contract. -/
theorem uniquelyIRPO_excludes_distinct_irpo
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily)
    (c d : Contract) (hunique : IsUniquelyIRPO E u c) (hne : d ≠ c) :
    ¬ IsIRPO E u d := by
  intro hd
  exact hne (hunique.2 d hd)

/-- Under significant-action utilities, taking the safe action has zero ex-post utility. -/
theorem significantAction_safe_zero (u : UtilityParameters)
    (hu : u.IsSignificantAction) (label rival : Bool) :
    u.exPost false label rival = 0 := by
  rw [UtilityParameters.exPost, hu.1, hu.2]
  simp

/-- Equation (2): when both firms take the same action, their combined payoff equals the
exclusive payoff for that action. -/
theorem shared_action_total (u : UtilityParameters) (action label : Bool) :
    u.exPost action label action + u.exPost action label action =
      (if action = label
        then if action then u.reward1 else u.reward0
        else -(if action then u.cost1 else u.cost0)) := by
  simp [UtilityParameters.exPost]

end TrainSharing
