import RequestProject.CorrelationModel
import RequestProject.TwoHypotheses

/-!
# Special models as instances of the general signaling model

This file supplies the missing bridge between the distribution-first Section 2 interfaces
and the paper's two concrete models.  First, every binary world model is turned into the
joint law of `(label, Firm 1 signal, Firm 2 signal)`, and a finite family of such worlds,
together with a prior and training experiment, becomes a `BayesianEnvironment`.

The correlation model is then embedded using its balanced label and reconstructed signal
laws.  The canonical finite presentation uses uninformative (`Unit`) training observations,
which is the information-equivalent reduction of Appendix D.1's randomly rotated interval
construction: each firm's posterior over the correlation remains its prior.

Finally, Figure 4's two-hypotheses laws are factored into a label law and conditional binary
signal laws.  Their induced joint inference law is proved equal to the law used in the
Section 5 development, so that model is literally an instance of the same general interface.
-/

namespace TrainSharing

namespace BinaryWorldModel

/-- Joint mass of a label and the two inference signals generated by a binary world. -/
def inferenceMass (M : BinaryWorldModel) (o : InferenceOutcome) : ℝ :=
  M.label.mass o.1 * (M.signals o.1).mass (o.2.1, o.2.2)

lemma inferenceMass_nonneg (M : BinaryWorldModel) (o : InferenceOutcome) :
    0 ≤ M.inferenceMass o := by
  exact mul_nonneg (M.label.nonneg o.1) ((M.signals o.1).nonneg (o.2.1, o.2.2))

lemma inferenceMass_total (M : BinaryWorldModel) :
    ∑ o, M.inferenceMass o = 1 := by
  calc
    ∑ o, M.inferenceMass o =
        ∑ t : Bool, M.label.mass t * ∑ s : Bool × Bool, (M.signals t).mass s := by
      rw [Fintype.sum_prod_type]
      congr 1
      funext t
      rw [Finset.mul_sum]
      congr 1
    _ = ∑ t : Bool, M.label.mass t * 1 := by
      congr 1
      funext t
      rw [(M.signals t).total]
    _ = 1 := by simpa using M.label.total

/-- The inference experiment generated by a Section 2 binary world. -/
def inferenceLaw (M : BinaryWorldModel) : FiniteLaw InferenceOutcome where
  mass := M.inferenceMass
  nonneg := M.inferenceMass_nonneg
  total := M.inferenceMass_total

end BinaryWorldModel

/-- A finite family of binary world models, with any finite training experiment, is a
finite instance of the paper's general Bayesian signaling environment. -/
def binarySignalingEnvironment
    {World Train1 Train2 : Type} [Fintype World] [Fintype Train1] [Fintype Train2]
    (prior : FiniteLaw World) (world : World → BinaryWorldModel)
    (training : World → FiniteLaw (Train1 × Train2)) :
    BayesianEnvironment World Train1 Train2 where
  prior := prior
  training := training
  inference w := (world w).inferenceLaw

/-- The probability-one law on the unique pair of uninformative training observations. -/
def uninformativeTrainingLaw : FiniteLaw (Unit × Unit) where
  mass := fun _ => 1
  nonneg := by intro; norm_num
  total := by simp

namespace Correlation

/-! ## A genuine finite correlation-training experiment

The `Unit` reduction below is useful only when training conveys no information even after
sharing.  It cannot represent the central case of Theorems 3.4 and 4.6, where each firm's
training observation is individually uninformative but the pair identifies the correlation.
For two correlation worlds, the XOR experiment is the exact finite analogue: nature draws
a fair bit `r` and sends `(r, r xor world)`.  Either coordinate is fair in either world,
while their XOR recovers the world.
-/

/-- Mass function for the two-world XOR training experiment. -/
noncomputable def xorTrainingMass (w : Bool) (z : Bool × Bool) : ℝ :=
  if xor z.1 z.2 = w then 1 / 2 else 0

/-- Each coordinate alone is uninformative, while the pair reveals the world. -/
noncomputable def xorTrainingLaw (w : Bool) : FiniteLaw (Bool × Bool) where
  mass := xorTrainingMass w
  nonneg z := by simp [xorTrainingMass]; positivity
  total := by
    fin_cases w
    · rw [show (Finset.univ : Finset (Bool × Bool)) =
        {(true, true), (true, false), (false, true), (false, false)} by decide]
      norm_num [xorTrainingMass]
    · rw [show (Finset.univ : Finset (Bool × Bool)) =
        {(true, true), (true, false), (false, true), (false, false)} by decide]
      norm_num [xorTrainingMass]

lemma xorTrainingLaw_first_marginal (w a : Bool) :
    ∑ b, (xorTrainingLaw w).mass (a, b) = 1 / 2 := by
  fin_cases w <;> fin_cases a <;>
    norm_num [xorTrainingLaw, xorTrainingMass, Finset.sum_eq_add_sum_diff_singleton]

lemma xorTrainingLaw_second_marginal (w b : Bool) :
    ∑ a, (xorTrainingLaw w).mass (a, b) = 1 / 2 := by
  fin_cases w <;> fin_cases b <;>
    norm_num [xorTrainingLaw, xorTrainingMass, Finset.sum_eq_add_sum_diff_singleton]

lemma xorTrainingLaw_pair_identifies (w : Bool) (z : Bool × Bool)
    (h : 0 < (xorTrainingLaw w).mass z) :
    xor z.1 z.2 = w := by
  simp only [xorTrainingLaw, xorTrainingMass] at h
  split at h <;> simp_all

/-- A two-world correlation model with the same accuracies in both worlds. -/
structure BinaryFiniteModel where
  prior : FiniteLaw Bool
  parameters : Bool → Parameters
  feasible : ∀ w, (parameters w).Feasible
  commonAlpha : (parameters false).alpha = (parameters true).alpha
  commonBeta : (parameters false).beta = (parameters true).beta

/-- The two-world correlation model embedded in the general signaling model using the
XOR training experiment. -/
noncomputable def BinaryFiniteModel.environment (C : BinaryFiniteModel) :
    BayesianEnvironment Bool Bool Bool :=
  binarySignalingEnvironment C.prior
    (fun w => (C.parameters w).world (C.feasible w)) xorTrainingLaw

@[simp] theorem BinaryFiniteModel.environment_training_mass
    (C : BinaryFiniteModel) (w : Bool) (z : Bool × Bool) :
    (C.environment.training w).mass z = xorTrainingMass w z := rfl

/-- A single firm's training signal has likelihood `1/2` in either correlation world. -/
theorem BinaryFiniteModel.training_firm1_uninformative
    (C : BinaryFiniteModel) (w a : Bool) :
    ∑ b, (C.environment.training w).mass (a, b) = 1 / 2 :=
  xorTrainingLaw_first_marginal w a

/-- The same holds for Firm 2. -/
theorem BinaryFiniteModel.training_firm2_uninformative
    (C : BinaryFiniteModel) (w b : Bool) :
    ∑ a, (C.environment.training w).mass (a, b) = 1 / 2 :=
  xorTrainingLaw_second_marginal w b

/-- Bayes' rule confirms that Firm 1's private training observation leaves its posterior
on correlation worlds equal to the prior. -/
theorem BinaryFiniteModel.posterior_firm1_eq_prior
    (C : BinaryFiniteModel) (a w : Bool) :
    C.environment.posteriorWorld .firm1 a w = C.prior.mass w := by
  have ht : C.prior.mass true + C.prior.mass false = 1 := by
    simpa [Finset.sum_eq_add_sum_diff_singleton] using C.prior.total
  fin_cases a <;>
  simp [BayesianEnvironment.posteriorWorld, BayesianEnvironment.trainingMass,
    BinaryFiniteModel.environment, binarySignalingEnvironment,
    xorTrainingLaw, xorTrainingMass] <;>
  rw [show C.prior.mass true * (2 : ℝ)⁻¹ + C.prior.mass false * 2⁻¹ = 1 / 2 by
    rw [← add_mul, ht]; norm_num] <;> norm_num

/-- Firm 2's private posterior likewise remains the prior. -/
theorem BinaryFiniteModel.posterior_firm2_eq_prior
    (C : BinaryFiniteModel) (b w : Bool) :
    C.environment.posteriorWorld .firm2 b w = C.prior.mass w := by
  have ht : C.prior.mass true + C.prior.mass false = 1 := by
    simpa [Finset.sum_eq_add_sum_diff_singleton] using C.prior.total
  fin_cases b <;>
  simp [BayesianEnvironment.posteriorWorld, BayesianEnvironment.trainingMass,
    BinaryFiniteModel.environment, binarySignalingEnvironment,
    xorTrainingLaw, xorTrainingMass] <;>
  rw [show C.prior.mass true * (2 : ℝ)⁻¹ + C.prior.mass false * 2⁻¹ = 1 / 2 by
    rw [← add_mul, ht]; norm_num] <;> norm_num

/-- Whenever a training pair has positive likelihood, it identifies the correlation
world exactly. -/
theorem BinaryFiniteModel.shared_training_identifies
    (C : BinaryFiniteModel) (w : Bool) (z : Bool × Bool)
    (h : 0 < (C.environment.training w).mass z) :
    xor z.1 z.2 = w :=
  xorTrainingLaw_pair_identifies w z h

/-- A finite prior over feasible correlation worlds with common accuracies.  This is the
finite/distributional counterpart of drawing `θ ∼ Θ` in Appendix D.1.  Its `Unit`
training observation is intentionally the degenerate special case in which even sharing
training data reveals nothing; use `BinaryFiniteModel` for Theorems 3.4 and 4.6. -/
structure FiniteModel (World : Type) [Fintype World] where
  prior : FiniteLaw World
  parameters : World → Parameters
  feasible : ∀ w, (parameters w).Feasible

/-- The correlation model as a concrete Section 2 Bayesian environment.  Its training
observations are uninformative about the realized correlation, exactly as established by
the random-rotation construction in Appendix D.1. -/
noncomputable def FiniteModel.environment
    {World : Type} [Fintype World] (C : FiniteModel World) :
    BayesianEnvironment World Unit Unit :=
  binarySignalingEnvironment C.prior
    (fun w => (C.parameters w).world (C.feasible w))
    (fun _ => uninformativeTrainingLaw)

@[simp] theorem FiniteModel.environment_prior
    {World : Type} [Fintype World] (C : FiniteModel World) :
    C.environment.prior = C.prior := rfl

@[simp] theorem FiniteModel.environment_training_mass
    {World : Type} [Fintype World] (C : FiniteModel World) (w : World) (z : Unit × Unit) :
    (C.environment.training w).mass z = 1 := rfl

/-- Neither firm learns anything about correlation from its canonical training observation. -/
theorem FiniteModel.posterior_firm1_eq_prior
    {World : Type} [Fintype World] (C : FiniteModel World) (w : World) :
    C.environment.posteriorWorld .firm1 () w = C.prior.mass w := by
  simp [BayesianEnvironment.posteriorWorld, BayesianEnvironment.trainingMass,
    FiniteModel.environment, binarySignalingEnvironment, uninformativeTrainingLaw,
    C.prior.total]

/-- Firm 2's canonical training observation likewise leaves its prior unchanged. -/
theorem FiniteModel.posterior_firm2_eq_prior
    {World : Type} [Fintype World] (C : FiniteModel World) (w : World) :
    C.environment.posteriorWorld .firm2 () w = C.prior.mass w := by
  simp [BayesianEnvironment.posteriorWorld, BayesianEnvironment.trainingMass,
    FiniteModel.environment, binarySignalingEnvironment, uninformativeTrainingLaw,
    C.prior.total]

/-- The conditional inference law in the embedded environment is exactly the correlation
world reconstructed in `CorrelationModel`. -/
@[simp] theorem FiniteModel.environment_inference_mass
    {World : Type} [Fintype World] (C : FiniteModel World)
    (w : World) (o : InferenceOutcome) :
    (C.environment.inference w).mass o =
      ((C.parameters w).world (C.feasible w)).label.mass o.1 *
        (((C.parameters w).world (C.feasible w)).signals o.1).mass (o.2.1, o.2.2) := rfl

end Correlation

namespace TwoHypothesesParameters

/-- The disease-incidence label law used in either hypothesis. -/
def labelLaw (x : TwoHypothesesParameters) (hx : x.Feasible) : FiniteLaw Bool where
  mass t := if t then x.k else 1 - x.k
  nonneg t := by
    cases t <;> simp
    · linarith [hx.2.2.2.1]
    · exact hx.2.2.1
  total := by simp

/-- Conditional signal table underlying Figure 4, before multiplying by label incidence. -/
def conditionalSignalMass (x : TwoHypothesesParameters)
    (w : Hypothesis) (t : Bool) : Bool × Bool → ℝ :=
  match w, t with
  | .I, true => fun s => if s = (true, true) then 1 else 0
  | .II, true => fun s => if s = (false, true) then 1 else 0
  | .I, false => fun
      | (true, false) => x.l
      | (false, true) => x.m
      | (false, false) => 1 - x.l - x.m
      | _ => 0
  | .II, false => fun
      | (true, true) => x.m
      | (true, false) => x.l
      | (false, false) => 1 - x.l - x.m
      | _ => 0

lemma conditionalSignalMass_nonneg (x : TwoHypothesesParameters) (hx : x.Feasible)
    (w : Hypothesis) (t : Bool) (s : Bool × Bool) :
    0 ≤ x.conditionalSignalMass w t s := by
  rcases hx with ⟨_, _, _, _, hl, hm, hlm⟩
  cases w <;> fin_cases t <;> fin_cases s <;>
    simp [conditionalSignalMass] <;> linarith

lemma conditionalSignalMass_total (x : TwoHypothesesParameters)
    (w : Hypothesis) (t : Bool) :
    ∑ s, x.conditionalSignalMass w t s = 1 := by
  cases w <;> fin_cases t <;>
    simp [conditionalSignalMass] <;>
    rw [show (Finset.univ : Finset (Bool × Bool)) =
      {(true, true), (true, false), (false, true), (false, false)} by decide] <;>
    simp
  all_goals ring

/-- The conditional signal law in a Figure 4 world. -/
def conditionalSignalLaw (x : TwoHypothesesParameters) (hx : x.Feasible)
    (w : Hypothesis) (t : Bool) : FiniteLaw (Bool × Bool) where
  mass := x.conditionalSignalMass w t
  nonneg := x.conditionalSignalMass_nonneg hx w t
  total := x.conditionalSignalMass_total w t

/-- Either hypothesis, viewed as a Section 2 binary world model. -/
def binaryWorld (x : TwoHypothesesParameters) (hx : x.Feasible)
    (w : Hypothesis) : BinaryWorldModel where
  label := x.labelLaw hx
  signals := x.conditionalSignalLaw hx w

/-- Factoring Figure 4 into label incidence and conditional signals recovers exactly its
previously used primitive joint inference mass. -/
theorem binaryWorld_inferenceMass (x : TwoHypothesesParameters) (hx : x.Feasible)
    (w : Hypothesis) (o : InferenceOutcome) :
    (x.binaryWorld hx w).inferenceMass o = x.inferenceMass w o := by
  cases w <;> fin_cases o <;>
    simp [BinaryWorldModel.inferenceMass, binaryWorld, labelLaw,
      conditionalSignalLaw, conditionalSignalMass, inferenceMass]

/-- Hence the Section 5 environment is equal to the general binary-signaling
construction equipped with the already-derived infinite-data training experiment. -/
theorem environment_eq_binarySignaling (x : TwoHypothesesParameters) (hx : x.Feasible) :
    x.environment hx =
      binarySignalingEnvironment (x.hypothesisLaw hx) (x.binaryWorld hx) trainingLaw := by
  rw [BayesianEnvironment.mk.injEq]
  refine ⟨rfl, rfl, ?_⟩
  funext w
  rw [FiniteLaw.mk.injEq]
  funext o
  exact (x.binaryWorld_inferenceMass hx w o).symm

end TwoHypothesesParameters

end TrainSharing
