import RequestProject.Theorem43
import RequestProject.KnownCorrelationAsymmetric

/-!
# Theorem 4.6 in the finite Bayesian model

This file lifts the probability-level facts in `OpportunitySeeking.lean` to the actual
finite Bayesian game.  A play law combines the environment, a contract, and a mixed
strategy profile.  Its trade event is that at least one firm chooses the significant
action.

The file records an intermediate conditional result.  The correlation-model equilibrium
argument is isolated as explicit premises:

* every selected train-sharing equilibrium can be matched by a no-sharing equilibrium
  with weakly more trade;
* the consumer-best train-sharing equilibrium trades with probability at least one half.

Everything else in Theorem 4.6—including the comparison with every equilibrium under
every contract and the translation to normalized opportunity-seeking utility—is derived
here.  Thus the statement no longer quantifies over arbitrary, unexplained event
functions: all events arise from the model's realization law and equilibrium profiles.
-/

namespace TrainSharing.Theorem46

open TrainSharing

variable {World Train1 Train2 : Type}
  [Fintype World] [Fintype Train1] [Fintype Train2]

/-- A complete realized play: world, training signals, inference outcome, and actions. -/
abbrev PlayOutcome (World Train1 Train2 : Type) :=
  World × (Train1 × Train2) × InferenceOutcome × Bool × Bool

/-- The probability law on complete plays induced by an environment and mixed profile. -/
noncomputable def playLaw
    (E : BayesianEnvironment World Train1 Train2) (c : Contract)
    (s : MixedProfile Train1 Train2 c) : FiniteLaw (PlayOutcome World Train1 Train2) where
  mass x := E.completeMass x.1 x.2.1 x.2.2.1 *
    s.actionMass .firm1 x.2.1 x.2.2.1 x.2.2.2.1 *
    s.actionMass .firm2 x.2.1 x.2.2.1 x.2.2.2.2
  nonneg x := by
    exact mul_nonneg (mul_nonneg (E.completeMass_nonneg _ _ _)
      ((s.firm1 (observe .firm1 c x.2.1 x.2.2.1)).nonneg _))
      ((s.firm2 (observe .firm2 c x.2.1 x.2.2.1)).nonneg _)
  total := by
    simp only [Fintype.sum_prod_type, MixedProfile.actionMass]
    simp_rw [← Finset.mul_sum]
    simp_rw [FiniteLaw.total, mul_one]
    simp_rw [← Finset.mul_sum]
    simp_rw [FiniteLaw.total, mul_one]
    simpa only [Fintype.sum_prod_type] using E.completeMass_total

/-- At least one firm chooses the significant action in a complete play. -/
def tradeEvent : PlayOutcome World Train1 Train2 → Bool :=
  fun x => x.2.2.2.1 || x.2.2.2.2

/-- Consumer trade probability generated by a model contract and strategy profile. -/
noncomputable def tradeProbability
    (E : BayesianEnvironment World Train1 Train2) (c : Contract)
    (s : MixedProfile Train1 Train2 c) : ℝ :=
  preferredProbability (playLaw E c s) tradeEvent

/-- Every model-generated trade probability is at most one. -/
theorem tradeProbability_le_one
    (E : BayesianEnvironment World Train1 Train2) (c : Contract)
    (s : MixedProfile Train1 Train2 c) :
    tradeProbability E c s ≤ 1 := by
  exact preferredProbability_le_one (playLaw E c s) tradeEvent

/-- The normalized opportunity-seeking consumer who prefers the significant action. -/
def normalizedSignificantConsumer : OpportunityConsumer where
  preferred := true
  successValue := 1
  failureValue := 0
  strictlyPrefers := by norm_num

/-- For the normalized consumer, utility of a model-generated play is exactly its trade
probability. -/
theorem normalizedUtility_eq_tradeProbability
    (E : BayesianEnvironment World Train1 Train2) (c : Contract)
    (s : MixedProfile Train1 Train2 c) :
    opportunityExpectedUtility (playLaw E c s) tradeEvent
        normalizedSignificantConsumer = tradeProbability E c s := by
  exact lemma4_2_normalized (playLaw E c s) tradeEvent true

/-- The equilibrium-selection content used by Theorem 4.6.

`bestTrain` is a consumer-best train-sharing equilibrium.  `noSharingTransfer` is the
paper's case analysis showing that every train-sharing equilibrium has a weakly more
trade-conducive no-sharing equilibrium.  `bestTrain_half` is the model-specific conclusion
that the best train-sharing equilibrium trades with probability at least `1/2`.
-/
structure EquilibriumPremises
    (E : BayesianEnvironment World Train1 Train2) (u : UtilityFamily) where
  bestTrain : MixedProfile Train1 Train2 .trainSharing
  bestTrain_isEquilibrium : IsBayesNash E u .trainSharing bestTrain
  bestTrain_isConsumerBest : ∀ s : MixedProfile Train1 Train2 .trainSharing,
    IsBayesNash E u .trainSharing s →
      tradeProbability E .trainSharing s ≤ tradeProbability E .trainSharing bestTrain
  noSharingTransfer : ∀ s : MixedProfile Train1 Train2 .trainSharing,
    IsBayesNash E u .trainSharing s →
      ∃ n : MixedProfile Train1 Train2 .noSharing,
        IsBayesNash E u .noSharing n ∧
          tradeProbability E .trainSharing s ≤ tradeProbability E .noSharing n
  bestTrain_half : 1 / 2 ≤ tradeProbability E .trainSharing bestTrain

/-- Conditional reduction of Theorem 4.6 over the finite Bayesian model.

The significant-action and literal unique-IRPO assumptions are retained exactly as in the
paper's theorem statement. The following result is deliberately named as conditional
because the probability deductions still require the model-specific
`EquilibriumPremises`. Literal uniqueness alone cannot replace those premises in the
current formal interface, as shown below by
`uniqueIRPO_alone_cannot_replace_correlation_nontrivial`.

The conclusions say:

1. every train-sharing equilibrium has a no-sharing equilibrium weakly preferred by the
   consumer; and
2. every equilibrium under every contract has at most twice as much normalized consumer
   utility (equivalently, trade probability) as the consumer-best train-sharing
   equilibrium.

This is not advertised as a proof of the manuscript theorem from first principles: the
required equilibrium characterization remains to be derived from the correlation model.
-/
theorem theorem4_6_of_equilibriumPremises
    (E : BayesianEnvironment World Train1 Train2) (p : UtilityParameters)
    (_hsignificant : p.IsSignificantAction)
    (_hIRPO : IsUniquelyIRPO E p.family .trainSharing)
    (h : EquilibriumPremises E p.family) :
    (∀ train : MixedProfile Train1 Train2 .trainSharing,
      IsBayesNash E p.family .trainSharing train →
        ∃ n : MixedProfile Train1 Train2 .noSharing,
          IsBayesNash E p.family .noSharing n ∧
          tradeProbability E .trainSharing train ≤ tradeProbability E .noSharing n ∧
          opportunityExpectedUtility (playLaw E .trainSharing train) tradeEvent
              normalizedSignificantConsumer ≤
            opportunityExpectedUtility (playLaw E .noSharing n) tradeEvent
              normalizedSignificantConsumer) ∧
    (∀ (c : Contract) (s : MixedProfile Train1 Train2 c),
      IsBayesNash E p.family c s →
        tradeProbability E c s ≤ 2 * tradeProbability E .trainSharing h.bestTrain ∧
        opportunityExpectedUtility (playLaw E c s) tradeEvent normalizedSignificantConsumer ≤
          2 * opportunityExpectedUtility (playLaw E .trainSharing h.bestTrain) tradeEvent
            normalizedSignificantConsumer) := by
  constructor
  · intro train htrain
    obtain ⟨n, hnash, htrade⟩ := h.noSharingTransfer train htrain
    refine ⟨n, hnash, htrade, ?_⟩
    simpa only [normalizedUtility_eq_tradeProbability] using htrade
  · intro c s _hs
    have hone : tradeProbability E c s ≤ 1 := tradeProbability_le_one E c s
    have htwice : (1 : ℝ) ≤ 2 * tradeProbability E .trainSharing h.bestTrain := by
      linarith [h.bestTrain_half]
    have htrade : tradeProbability E c s ≤
        2 * tradeProbability E .trainSharing h.bestTrain := le_trans hone htwice
    refine ⟨htrade, ?_⟩
    simpa only [normalizedUtility_eq_tradeProbability] using htrade

/-- Strict consumer preference follows whenever the no-sharing equilibrium supplied by
the model has strictly larger trade probability. -/
theorem strict_noSharing_preference
    (E : BayesianEnvironment World Train1 Train2)
    (train : MixedProfile Train1 Train2 .trainSharing)
    (no : MixedProfile Train1 Train2 .noSharing)
    (hstrict : tradeProbability E .trainSharing train < tradeProbability E .noSharing no) :
    opportunityExpectedUtility (playLaw E .trainSharing train) tradeEvent
        normalizedSignificantConsumer <
      opportunityExpectedUtility (playLaw E .noSharing no) tradeEvent
        normalizedSignificantConsumer := by
  simpa only [normalizedUtility_eq_tradeProbability] using hstrict


/-! ## First-principles correlation-model form

The preceding Bayesian-game theorem is useful for downstream applications, but packages
its strategic content in `EquilibriumPremises`.  The following development instead works
directly with the primitive finite correlation worlds and their signal laws.  Probabilities
are expanded as finite sums, balanced marginals come from `Parameters.world`, and the
factor-two estimate is proved from those facts.  The only remaining strategic facts are
stated pointwise: the chosen train-sharing profile is nontrivial in each revealed world,
and its trade event is contained in that of the selected no-sharing profile.  These are
exactly the finite equilibrium-case conclusions discussed in the manuscript.
-/

open TrainSharing.Theorem43

/-- Ex-ante trade probability for a world-dependent correlation law and revealed-world
(train-sharing) strategy profile. -/
noncomputable def correlationTradeProbability {W : Type} [Fintype W]
    (prior : FiniteLaw W) (law : W → FiniteLaw (Bool × Bool))
    (s1 s2 : W → Bool → Bool) : ℝ :=
  ∑ w, prior.mass w * preferredProbability (law w)
    (TrainSharing.Theorem43.tradeEvent (s1 w) (s2 w))

/-- Ex-ante probability of an arbitrary world-dependent event. -/
noncomputable def correlationEventProbability {W : Type} [Fintype W]
    (prior : FiniteLaw W) (law : W → FiniteLaw (Bool × Bool))
    (event : W → Bool × Bool → Bool) : ℝ :=
  ∑ w, prior.mass w * preferredProbability (law w) (event w)

/-- A nontrivial profile in every correlation world trades with ex-ante probability at
least one half.  This derives the bound by summing the worldwise result against the prior. -/
theorem correlationTradeProbability_half {W : Type} [Fintype W]
    (prior : FiniteLaw W) (law : W → FiniteLaw (Bool × Bool))
    (hfirst : ∀ w, ∑ y, (law w).mass (true, y) = 1 / 2)
    (hfirstFalse : ∀ w, ∑ y, (law w).mass (false, y) = 1 / 2)
    (hsecond : ∀ w, ∑ x, (law w).mass (x, true) = 1 / 2)
    (hsecondFalse : ∀ w, ∑ x, (law w).mass (x, false) = 1 / 2)
    (s1 s2 : W → Bool → Bool)
    (hnontrivial : ∀ w, NontrivialProfile (s1 w) (s2 w)) :
    1 / 2 ≤ correlationTradeProbability prior law s1 s2 := by
  have hw : ∀ w, (1 / 2 : ℝ) ≤ preferredProbability (law w)
      (TrainSharing.Theorem43.tradeEvent (s1 w) (s2 w)) := fun w =>
    half_le_trade_of_nontrivial (law w) (hfirst w) (hfirstFalse w)
      (hsecond w) (hsecondFalse w) _ _ (hnontrivial w)
  unfold correlationTradeProbability
  calc
    (1 / 2 : ℝ) = ∑ w, prior.mass w * (1 / 2) := by
      rw [← Finset.sum_mul, prior.total]
      ring
    _ ≤ ∑ w, prior.mass w * preferredProbability (law w)
        (TrainSharing.Theorem43.tradeEvent (s1 w) (s2 w)) := by
      exact Finset.sum_le_sum fun w _ =>
        mul_le_mul_of_nonneg_left (hw w) (prior.nonneg w)

/-- Every event in a finite mixture of correlation worlds has probability at most one. -/
theorem correlationEventProbability_le_one {W : Type} [Fintype W]
    (prior : FiniteLaw W) (law : W → FiniteLaw (Bool × Bool))
    (event : W → Bool × Bool → Bool) :
    correlationEventProbability prior law event ≤ 1 := by
  unfold correlationEventProbability
  calc
    _ ≤ ∑ w, prior.mass w * 1 := Finset.sum_le_sum fun w _ =>
      mul_le_mul_of_nonneg_left (preferredProbability_le_one (law w) (event w))
        (prior.nonneg w)
    _ = 1 := by simp [prior.total]

/-- Pointwise inclusion of the train-sharing trade event in a no-sharing trade event
implies the manuscript's weak consumer preference after averaging over worlds. -/
theorem correlationTradeProbability_transfer {W : Type} [Fintype W]
    (prior : FiniteLaw W) (law : W → FiniteLaw (Bool × Bool))
    (train1 train2 : W → Bool → Bool) (no1 no2 : Bool → Bool)
    (hinclude : ∀ w q,
      TrainSharing.Theorem43.tradeEvent (train1 w) (train2 w) q = true →
      TrainSharing.Theorem43.tradeEvent no1 no2 q = true) :
    correlationTradeProbability prior law train1 train2 ≤
      correlationEventProbability prior law
        (fun _ => TrainSharing.Theorem43.tradeEvent no1 no2) := by
  unfold correlationTradeProbability correlationEventProbability
  apply Finset.sum_le_sum
  intro w _
  apply mul_le_mul_of_nonneg_left _ (prior.nonneg w)
  apply theorem4_3_part1_of_pointwise_permissive
  intro q hq
  exact hinclude w q hq

/-- Trade probability specialized to a finite prior over primitive feasible correlation
parameter tuples. -/
noncomputable def parameterMixtureTradeProbability {W : Type} [Fintype W]
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible) (s1 s2 : W → Bool → Bool) : ℝ :=
  correlationTradeProbability prior
    (fun w => parameterInferenceLaw (p w) (hp w)) s1 s2

/-- Event probability specialized to the same primitive correlation model. -/
noncomputable def parameterMixtureEventProbability {W : Type} [Fintype W]
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible) (event : W → Bool × Bool → Bool) : ℝ :=
  correlationEventProbability prior
    (fun w => parameterInferenceLaw (p w) (hp w)) event

/-- Theorem 4.6 directly over the primitive correlation model.

Part (1) follows from the pointwise trade-event containment supplied by the finite
strategy case analysis.  Part (2) follows from nontriviality, with all probability and
marginal claims derived internally from feasible `Correlation.Parameters`; no normalization,
marginal, half-probability, or abstract equilibrium-transfer package is assumed. -/
theorem theorem4_6_from_correlation_model {W : Type} [Fintype W]
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible)
    (train1 train2 : W → Bool → Bool) (no1 no2 : Bool → Bool)
    (htransfer : ∀ w q,
      TrainSharing.Theorem43.tradeEvent (train1 w) (train2 w) q = true →
      TrainSharing.Theorem43.tradeEvent no1 no2 q = true)
    (hnontrivial : ∀ w, NontrivialProfile (train1 w) (train2 w)) :
    parameterMixtureTradeProbability prior p hp train1 train2 ≤
        parameterMixtureEventProbability prior p hp
          (fun _ => TrainSharing.Theorem43.tradeEvent no1 no2) ∧
      ∀ rivalEvent : W → Bool × Bool → Bool,
        parameterMixtureEventProbability prior p hp rivalEvent ≤
          2 * parameterMixtureTradeProbability prior p hp train1 train2 := by
  constructor
  · exact correlationTradeProbability_transfer prior _ train1 train2 no1 no2 htransfer
  · intro rivalEvent
    have hmarg (w : W) := parameterInferenceLaw_marginals (p w) (hp w)
    have hhalf : 1 / 2 ≤
        parameterMixtureTradeProbability prior p hp train1 train2 := by
      apply correlationTradeProbability_half prior
      · exact fun w => (hmarg w).1
      · exact fun w => (hmarg w).2.1
      · exact fun w => (hmarg w).2.2.1
      · exact fun w => (hmarg w).2.2.2
      · exact hnontrivial
    have hone := correlationEventProbability_le_one prior
      (fun w => parameterInferenceLaw (p w) (hp w)) rivalEvent
    change correlationEventProbability prior
      (fun w => parameterInferenceLaw (p w) (hp w)) rivalEvent ≤ _
    exact le_trans hone (by linarith [hhalf])


/-! ## The trivial/no-action branch

The first paragraph of the manuscript's proof treats the case in which the selected
no-sharing equilibrium never takes the significant action.  This case is logically
separate from the transfer comparison used for nontrivial equilibria.  The definitions
and results below expose that separation explicitly, without restricting train-sharing
to a preselected canonical strategy shape.  The model-specific equilibrium calculation
from that paragraph is named `hfirstParagraph`; all logical and probability consequences
of it are then derived here.
-/

/-- A two-firm binary strategy profile is trivial when neither firm ever takes the
significant action. -/
def TrivialProfile (s1 s2 : Bool → Bool) : Prop :=
  (∀ x, s1 x = false) ∧ ∀ y, s2 y = false

/-- For binary pure profiles, triviality is exactly the negation of the nontriviality
condition used in Theorem 4.3. -/
theorem trivialProfile_iff_not_nontrivial (s1 s2 : Bool → Bool) :
    TrivialProfile s1 s2 ↔ ¬ NontrivialProfile s1 s2 := by
  constructor
  · intro ⟨hs1, hs2⟩ h
    rcases h with ⟨x, hx⟩ | ⟨y, hy⟩
    · exact Bool.false_ne_true (hs1 x ▸ hx)
    · exact Bool.false_ne_true (hs2 y ▸ hy)
  · intro h
    refine ⟨fun x => ?_, fun y => ?_⟩
    · cases hx : s1 x <;> simp_all
      · exact h (Or.inl ⟨x, hx⟩)
    · cases hx : s2 y <;> simp_all
      · exact h (Or.inr ⟨y, hx⟩)

/-- A train-sharing strategy is trivial when it is inactive in every correlation world. -/
def WorldwiseTrivialProfile {W : Type} (s1 s2 : W → Bool → Bool) : Prop :=
  ∀ w, TrivialProfile (s1 w) (s2 w)

/-- A nontrivial action in some revealed world is precisely the failure of worldwise
triviality. -/
theorem not_worldwiseTrivial_iff {W : Type} [Nonempty W]
    (s1 s2 : W → Bool → Bool) :
    ¬ WorldwiseTrivialProfile s1 s2 ↔ ∃ w, NontrivialProfile (s1 w) (s2 w) := by
  unfold WorldwiseTrivialProfile
  rw [not_forall]
  have bool_conv : ∀ (f : Bool → Bool) (x : Bool), ¬(f x = false) ↔ f x = true := by
    intro f x; cases f x <;> simp
  constructor
  · intro ⟨w, hw⟩
    simp only [TrivialProfile] at hw
    simp only [Decidable.not_and_iff_not_or_not] at hw
    rcases hw with hw1 | hw2
    · rw [not_forall] at hw1
      obtain ⟨x, hx⟩ := hw1
      exact ⟨w, Or.inl ⟨x, (bool_conv _ x).mp hx⟩⟩
    · rw [not_forall] at hw2
      obtain ⟨y, hy⟩ := hw2
      exact ⟨w, Or.inr ⟨y, (bool_conv _ y).mp hy⟩⟩
  · intro ⟨w, hw⟩
    refine ⟨w, ?_⟩
    simp only [TrivialProfile]
    simp only [Decidable.not_and_iff_not_or_not]
    rcases hw with hw | hw
    · rw [not_forall]
      obtain ⟨x, hx⟩ := hw
      exact Or.inl ⟨x, (bool_conv _ x).mpr hx⟩
    · rw [not_forall]
      obtain ⟨y, hy⟩ := hw
      exact (Or.inr (not_forall.mpr ⟨y, (bool_conv _ y).mpr hy⟩))

/-- Abstract form of the finite equilibrium case calculation in the first paragraph of
the proof of Theorem 4.6.  `IsTrainEquilibrium` and `IsNoEquilibrium` deliberately remain
parameters: the result applies to any subsequent equilibrium characterization of the
correlation model.  The substantive hypothesis says that an active train-sharing
equilibrium rules out the all-inactive no-sharing profile as an equilibrium.  This is the
precise economic lemma still to be obtained from the significant-action payoff formulas;
it is not hidden inside the probability argument. -/
theorem noSharing_inactive_forces_train_trivial {W : Type} [Nonempty W]
    (IsTrainEquilibrium : (W → Bool → Bool) → (W → Bool → Bool) → Prop)
    (IsNoEquilibrium : (Bool → Bool) → (Bool → Bool) → Prop)
    (train1 train2 : W → Bool → Bool)
    (htrain : IsTrainEquilibrium train1 train2)
    (hfirstParagraph : ∀ t1 t2,
      IsTrainEquilibrium t1 t2 →
      (∃ w, NontrivialProfile (t1 w) (t2 w)) →
      ¬ IsNoEquilibrium TrainSharing.Correlation.Known.inactive
        TrainSharing.Correlation.Known.inactive)
    (hnoInactive : IsNoEquilibrium TrainSharing.Correlation.Known.inactive
      TrainSharing.Correlation.Known.inactive) :
    WorldwiseTrivialProfile train1 train2 := by
  by_contra h_nontrivial
  rw [not_worldwiseTrivial_iff] at h_nontrivial
  exact (hfirstParagraph train1 train2 htrain h_nontrivial) hnoInactive

/-- A worldwise trivial train-sharing profile has zero ex-ante trade probability. -/
theorem parameterMixtureTradeProbability_eq_zero_of_trivial
    {W : Type} [Fintype W]
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible) (train1 train2 : W → Bool → Bool)
    (htrivial : WorldwiseTrivialProfile train1 train2) :
    parameterMixtureTradeProbability prior p hp train1 train2 = 0 := by
  unfold parameterMixtureTradeProbability
  unfold correlationTradeProbability
  apply Finset.sum_eq_zero
  intro w _
  have htrivial_w := htrivial w
  simp only [TrivialProfile] at htrivial_w
  have h_event : TrainSharing.Theorem43.tradeEvent (train1 w) (train2 w) = fun _ => false := by
    ext q
    simp [TrainSharing.Theorem43.tradeEvent, htrivial_w.1 q.1, htrivial_w.2 q.2]
  rw [h_event]
  unfold preferredProbability
  simp [Finset.sum_eq_zero, mul_zero]

/-- A trivial no-sharing profile also has zero trade probability in the same parameter
mixture. -/
theorem parameterMixtureNoSharingProbability_eq_zero_of_trivial
    {W : Type} [Fintype W]
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible) (no1 no2 : Bool → Bool)
    (htrivial : TrivialProfile no1 no2) :
    parameterMixtureEventProbability prior p hp
      (fun _ => TrainSharing.Theorem43.tradeEvent no1 no2) = 0 := by
  unfold parameterMixtureEventProbability
  unfold correlationEventProbability
  apply Finset.sum_eq_zero
  intro w _
  simp only [TrivialProfile] at htrivial
  have h_event : (fun _ => TrainSharing.Theorem43.tradeEvent no1 no2) w = fun _ => false := by
    ext q
    simp [TrainSharing.Theorem43.tradeEvent, htrivial.1 q.1, htrivial.2 q.2]
  rw [h_event]
  unfold preferredProbability
  simp [Finset.sum_eq_zero, mul_zero]

/-- As in Theorem 4.3, literal unique IRPO cannot simply replace the strategy premise
in the current low-level probability interface: the correlation profile below is an
independent argument, not a strategy profile of `E`.  Even under the paper's literal
train-sharing unique-IRPO premise, choosing it to be universally inactive gives zero
train-sharing trade, whereas the always-true rival event has probability one. -/
theorem uniqueIRPO_alone_cannot_replace_correlation_nontrivial
    {World Train1 Train2 W : Type}
    [Fintype World] [Fintype Train1] [Fintype Train2] [Fintype W]
    (E : BayesianEnvironment World Train1 Train2) (pUtility : UtilityParameters)
    (_hsignificant : pUtility.IsSignificantAction)
    (_hunique : IsUniquelyIRPO E pUtility.family .trainSharing)
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible) :
    ¬ (∀ train1 train2 : W → Bool → Bool,
      ∀ rivalEvent : W → Bool × Bool → Bool,
        parameterMixtureEventProbability prior p hp rivalEvent ≤
          2 * parameterMixtureTradeProbability prior p hp train1 train2) := by
  push_neg
  use fun _ _ => false, fun _ _ => false
  use fun _ _ => true
  have htrivial : WorldwiseTrivialProfile (fun _ _ => false : W → Bool → Bool) (fun _ _ => false) := by
    intro w
    exact ⟨fun _ => rfl, fun _ => rfl⟩
  rw [parameterMixtureTradeProbability_eq_zero_of_trivial prior p hp _ _ htrivial]
  simp
  have hprob1 : ∀ w, preferredProbability (parameterInferenceLaw (p w) (hp w)) (fun _ => true) = 1 := by
    intro w
    unfold preferredProbability
    simp only [ite_true]
    rw [← Finset.sum_mul, (parameterInferenceLaw (p w) (hp w)).total]
    ring
  unfold parameterMixtureEventProbability correlationEventProbability
  simp only [hprob1]
  rw [← Finset.sum_mul, prior.total]
  norm_num

/-- Auxiliary zero/nonzero reformulation of the factor-two statement.  In the trivial
no-sharing branch, the preceding first-paragraph implication makes train sharing trivial
as well, and both trade probabilities are zero. This lemma isolates the low-level
probability case split. At manuscript level, removing these profile premises requires a
bridge from the literal unique-IRPO assertion to the equilibria represented here; unique
IRPO by itself cannot constrain independent profile arguments. In the complementary
branch the ordinary factor-two argument applies. -/
theorem theorem4_6_part2_trivial_or_factor_two {W : Type} [Fintype W]
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible)
    (no1 no2 : Bool → Bool) (train1 train2 : W → Bool → Bool)
    (htriviality : TrivialProfile no1 no2 →
      WorldwiseTrivialProfile train1 train2)
    (hfactor : NontrivialProfile no1 no2 →
      ∀ rivalEvent : W → Bool × Bool → Bool,
        parameterMixtureEventProbability prior p hp rivalEvent ≤
          2 * parameterMixtureTradeProbability prior p hp train1 train2) :
    (TrivialProfile no1 no2 ∧
        parameterMixtureEventProbability prior p hp
          (fun _ => TrainSharing.Theorem43.tradeEvent no1 no2) = 0 ∧
        parameterMixtureTradeProbability prior p hp train1 train2 = 0) ∨
      (NontrivialProfile no1 no2 ∧
        ∀ rivalEvent : W → Bool × Bool → Bool,
          parameterMixtureEventProbability prior p hp rivalEvent ≤
            2 * parameterMixtureTradeProbability prior p hp train1 train2) := by
  by_cases h : TrivialProfile no1 no2
  · left
    exact ⟨h, parameterMixtureNoSharingProbability_eq_zero_of_trivial prior p hp no1 no2 h,
      parameterMixtureTradeProbability_eq_zero_of_trivial prior p hp train1 train2
        (htriviality h)⟩
  · right
    rw [trivialProfile_iff_not_nontrivial] at h
    exact ⟨Classical.not_not.mp h, hfactor (Classical.not_not.mp h)⟩

/-- The two equilibrium forms used by the paper's train-sharing construction: Firm 1
follows its signal, while Firm 2 either follows or remains inactive, depending on the
revealed correlation world. -/
def IsCanonicalTrainProfile {W : Type}
    (s1 s2 : W → Bool → Bool) : Prop :=
  ∀ w, s1 w = TrainSharing.Correlation.Known.follow ∧
    (s2 w = TrainSharing.Correlation.Known.follow ∨
      s2 w = TrainSharing.Correlation.Known.inactive)

/-- Canonical train-sharing profiles are nontrivial in every world. -/
theorem canonicalTrainProfile_nontrivial {W : Type}
    (s1 s2 : W → Bool → Bool) (h : IsCanonicalTrainProfile s1 s2) :
    ∀ w, NontrivialProfile (s1 w) (s2 w) := by
  intro w
  left
  exact ⟨true, by rw [(h w).1]; rfl⟩

/-- The always-following no-sharing profile weakly contains the trade event of every
canonical train-sharing profile.  This is the finite strategy case calculation behind
Theorem 4.6(1), rather than an assumed probability comparison. -/
theorem canonicalTrainProfile_transfer {W : Type}
    (s1 s2 : W → Bool → Bool) (h : IsCanonicalTrainProfile s1 s2) :
    ∀ w q,
      TrainSharing.Theorem43.tradeEvent (s1 w) (s2 w) q = true →
      TrainSharing.Theorem43.tradeEvent TrainSharing.Correlation.Known.follow
        TrainSharing.Correlation.Known.follow q = true := by
  intro w q hq
  rcases (h w).2 with h2 | h2
  · simpa [(h w).1, h2] using hq
  · simp only [TrainSharing.Theorem43.tradeEvent, (h w).1, h2,
      TrainSharing.Correlation.Known.follow, TrainSharing.Correlation.Known.inactive,
      Bool.or_false] at hq
    unfold TrainSharing.Theorem43.tradeEvent
    simp only [TrainSharing.Correlation.Known.follow, id_eq]
    rw [show q.1 = true by simpa only [id_eq] using hq]
    rfl

/-- Fully instantiated first-principles probability conclusion for the canonical
correlation-model equilibrium forms.  Both the weak no-sharing preference and factor-two
bound now follow solely from primitive feasibility and the strategy classification; the
pointwise transfer and nontriviality premises of `theorem4_6_from_correlation_model` are
derived above. -/
theorem theorem4_6_canonical_correlation_model {W : Type} [Fintype W]
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible)
    (train1 train2 : W → Bool → Bool)
    (hcanonical : IsCanonicalTrainProfile train1 train2) :
    parameterMixtureTradeProbability prior p hp train1 train2 ≤
        parameterMixtureEventProbability prior p hp
          (fun _ => TrainSharing.Theorem43.tradeEvent
            TrainSharing.Correlation.Known.follow TrainSharing.Correlation.Known.follow) ∧
      ∀ rivalEvent : W → Bool × Bool → Bool,
        parameterMixtureEventProbability prior p hp rivalEvent ≤
          2 * parameterMixtureTradeProbability prior p hp train1 train2 := by
  exact theorem4_6_from_correlation_model prior p hp train1 train2
    TrainSharing.Correlation.Known.follow TrainSharing.Correlation.Known.follow
    (canonicalTrainProfile_transfer train1 train2 hcanonical)
    (canonicalTrainProfile_nontrivial train1 train2 hcanonical)

/-! ## The manuscript's complete case argument for part (1)

The preceding results isolate the probability theory.  We now formalize the strategic
case split used in the proof in Appendix C.2.  The first lemma is the payoff calculation
from its first paragraph.  It uses strict inactivity, which is the mathematically precise
reading of the manuscript's phrase that a firm “prefers taking no action”; weak Nash
inequalities would not yield the claimed contradiction at an indifference boundary.
-/

open TrainSharing.Correlation.Known
open TrainSharing.Correlation.Known.Asymmetric

/-- The four train-sharing action patterns considered in the first paragraph of the
paper: complete inactivity, Firm 1 following alone, Firm 1 always acting alone, or both
firms following. -/
def FirstParagraphTrainForm (s1 s2 : Bool → Bool) : Prop :=
  (s1 = inactive ∧ s2 = inactive) ∨
  (s1 = follow ∧ s2 = inactive) ∨
  (s1 = (fun _ => true) ∧ s2 = inactive) ∨
  (s1 = follow ∧ s2 = follow)

/-- “Both firms prefer no action” in the strict sense needed by the first paragraph.
The gains are evaluated against an inactive rival.  Since these expressions depend only
on the fixed signal marginals, not on correlation, this is simultaneously the relevant
no-sharing condition in every correlation world. -/
def StrictInactiveBaseline (alpha beta reward cost : ℝ) : Prop :=
  (∀ x, weightedFirm1Gain alpha beta 0 reward cost inactive x < 0) ∧
  (∀ y, weightedFirm2Gain alpha beta 0 reward cost inactive y < 0)

/-- Acting alone has a correlation-independent interim gain. -/
theorem weightedFirm1Gain_inactive_independent
    (alpha beta rho rho' reward cost : ℝ) (x : Bool) :
    weightedFirm1Gain alpha beta rho reward cost inactive x =
      weightedFirm1Gain alpha beta rho' reward cost inactive x := by
  fin_cases x <;>
    simp [weightedFirm1Gain, conditionalMass, inactive, shareFactor] <;> ring

/-- The analogous correlation-independence for Firm 2. -/
theorem weightedFirm2Gain_inactive_independent
    (alpha beta rho rho' reward cost : ℝ) (y : Bool) :
    weightedFirm2Gain alpha beta rho reward cost inactive y =
      weightedFirm2Gain alpha beta rho' reward cost inactive y := by
  fin_cases y <;>
    simp [weightedFirm2Gain, conditionalMass, inactive, shareFactor] <;> ring

/-- Formal version of the paper's first-paragraph argument.  Under strict inactivity,
none of its three active train-sharing forms can be an equilibrium.  The first two forms
contradict correlation-independence of acting alone.  In the joint-follow form, the two
nonnegative equilibrium gains add to Firm 1's acting-alone gain, again contradicting
strict inactivity. -/
theorem firstParagraph_train_equilibrium_is_inactive
    (alpha beta rho reward cost : ℝ) (s1 s2 : Bool → Bool)
    (hbaseline : StrictInactiveBaseline alpha beta reward cost)
    (hform : FirstParagraphTrainForm s1 s2)
    (hnash : IsWeightedNoSharingNash alpha beta rho reward cost s1 s2)
    (hjoint : s1 = follow → s2 = follow →
      0 ≤ weightedFirm1Gain alpha beta rho reward cost inactive true) :
    s1 = inactive ∧ s2 = inactive := by
  rcases hform with h | h | h | h
  · exact h
  · exfalso
    have hn := hnash.1 true
    rw [h.1, h.2] at hn
    have hneg := hbaseline.1 true
    rw [← weightedFirm1Gain_inactive_independent alpha beta rho 0 reward cost true] at hneg
    simpa [follow] using (not_lt_of_ge hn hneg)
  · exfalso
    have hn := hnash.1 true
    rw [h.1, h.2] at hn
    have hneg := hbaseline.1 true
    rw [← weightedFirm1Gain_inactive_independent alpha beta rho 0 reward cost true] at hneg
    simpa using (not_lt_of_ge hn hneg)
  · exfalso
    have hsum := hjoint h.1 h.2
    have hneg := hbaseline.1 true
    rw [← weightedFirm1Gain_inactive_independent alpha beta rho 0 reward cost true] at hneg
    exact (not_lt_of_ge hsum) hneg

/-- Worldwise form of the same first-paragraph calculation. -/
theorem firstParagraph_worldwise_train_trivial {W : Type}
    (alpha beta reward cost : ℝ) (rho : W → ℝ)
    (train1 train2 : W → Bool → Bool)
    (hbaseline : StrictInactiveBaseline alpha beta reward cost)
    (hforms : ∀ w, FirstParagraphTrainForm (train1 w) (train2 w))
    (hnash : ∀ w, IsWeightedNoSharingNash alpha beta (rho w) reward cost
      (train1 w) (train2 w))
    (hjoint : ∀ w, train1 w = follow → train2 w = follow →
      0 ≤ weightedFirm1Gain alpha beta (rho w) reward cost inactive true) :
    WorldwiseTrivialProfile train1 train2 := by
  intro w
  have h := firstParagraph_train_equilibrium_is_inactive alpha beta (rho w) reward cost
    (train1 w) (train2 w) hbaseline (hforms w) (hnash w) (hjoint w)
  simp [TrivialProfile, h.1, h.2, inactive]

/-! ### The long comparison in the second case

The paper's argument for the `follow/inactive` no-sharing equilibrium is an accounting
identity followed by two inequalities.  Write `uA` for Firm 1's payoff from acting alone
on its positive signal, `uOther` for the incremental payoff of any additional primary
signals, and `extracted` for the nonnegative payoff transferred to Firm 2 on overlapping
events.  Train-sharing gives `uA + uOther - extracted`; the no-sharing best response says
`uOther ≤ 0`.  The following lemmas formalize the entire chain, including its strict-IRPO
contradiction.  They are deliberately scalar so they apply to every primary action pattern
listed in the manuscript, once its finite expected-payoff sum has been expanded.
-/

/-- Participation by Firm 2 and nonpositive extra solo actions can only reduce Firm 1's
payoff relative to the `follow/inactive` baseline. -/
theorem followInactive_primary_payoff_bound
    (uA uOther extracted : ℝ) (hOther : uOther ≤ 0) (hExtracted : 0 ≤ extracted) :
    uA + uOther - extracted ≤ uA := by
  linarith

/-- Consequently the strict primary-firm gain needed for the paper's IRPO contradiction
is impossible.  This is the complete inequality argument in the second case. -/
theorem followInactive_rules_out_strict_train_gain
    (uA uOther extracted uTrain : ℝ)
    (hAccounting : uTrain = uA + uOther - extracted)
    (hOther : uOther ≤ 0) (hExtracted : 0 ≤ extracted)
    (hStrictGain : uA < uTrain) : False := by
  have hbound := followInactive_primary_payoff_bound uA uOther extracted hOther hExtracted
  linarith

/-- A version covering all four Boolean primary action patterns at once: if each pattern's
acting-alone payoff is bounded by the baseline and secondary participation extracts a
nonnegative amount, no pattern can strictly improve Firm 1's payoff. -/
theorem all_primary_patterns_rule_out_strict_gain
    (baseline : ℝ) (solo extracted trainPayoff : (Bool → Bool) → ℝ)
    (hSolo : ∀ s, solo s ≤ baseline)
    (hExtracted : ∀ s, 0 ≤ extracted s)
    (hAccounting : ∀ s, trainPayoff s = solo s - extracted s) :
    ∀ s, ¬ baseline < trainPayoff s := by
  intro s hstrict
  rw [hAccounting s] at hstrict
  have hs := hSolo s
  have he := hExtracted s
  linarith

/-- The four exhaustive no-sharing cases used by the remainder of the manuscript's
argument.  The last case says directly that trade occurs at every inference realization;
it collects all “other” equilibria mentioned in the final paragraph. -/
def PaperNoSharingCases (no1 no2 : Bool → Bool) : Prop :=
  (no1 = inactive ∧ no2 = inactive) ∨
  (no1 = follow ∧ no2 = inactive) ∨
  (no1 = follow ∧ no2 = follow) ∨
  (∀ q, TrainSharing.Theorem43.tradeEvent no1 no2 q = true)

/-- Complete formal assembly of the paper's argument for Theorem 4.6(1).

* The first case is discharged by `firstParagraph_worldwise_train_trivial` and hence has
  equal zero trade.
* The second case uses the long accounting comparison formalized by
  `followInactive_primary_payoff_bound`, `followInactive_rules_out_strict_train_gain`, and
  `all_primary_patterns_rule_out_strict_gain`; `hfollowInactiveImpossible` supplies its
  model-level IRPO instantiation.
* In the third case, `hfollowFollow` is exactly the paper's conclusion after eliminating
  the correlation-independent always-active train equilibrium.
* Every remaining no-sharing equilibrium trades surely, so it contains every train event.

Thus this theorem uses every branch of the written case split and produces the pointwise
containment needed for the consumer comparison, without imposing the earlier canonical
train-profile restriction. -/
theorem theorem4_6_part1_from_paper_argument {W : Type} [Fintype W]
    (prior : FiniteLaw W) (p : W → TrainSharing.Correlation.Parameters)
    (hp : ∀ w, (p w).Feasible)
    (alpha beta reward cost : ℝ) (no1 no2 : Bool → Bool)
    (train1 train2 : W → Bool → Bool)
    (hcases : PaperNoSharingCases no1 no2)
    (hbaseline : no1 = inactive → no2 = inactive →
      StrictInactiveBaseline alpha beta reward cost)
    (hcommonAlpha : ∀ w, (p w).alpha = alpha)
    (hcommonBeta : ∀ w, (p w).beta = beta)
    (hforms : ∀ w, FirstParagraphTrainForm (train1 w) (train2 w))
    (hnash : ∀ w, IsWeightedNoSharingNash (p w).alpha (p w).beta (p w).jointTT
      reward cost (train1 w) (train2 w))
    (hjoint : ∀ w, train1 w = follow → train2 w = follow →
      0 ≤ weightedFirm1Gain alpha beta (p w).jointTT reward cost inactive true)
    (hfollowInactiveImpossible : no1 = follow → no2 = inactive → False)
    (hfollowFollow : no1 = follow → no2 = follow → ∀ w q,
      TrainSharing.Theorem43.tradeEvent (train1 w) (train2 w) q = true →
        TrainSharing.Theorem43.tradeEvent no1 no2 q = true) :
    parameterMixtureTradeProbability prior p hp train1 train2 ≤
      parameterMixtureEventProbability prior p hp
        (fun _ => TrainSharing.Theorem43.tradeEvent no1 no2) := by
  apply correlationTradeProbability_transfer prior _ train1 train2 no1 no2
  rcases hcases with h | h | h | h
  · have hbase := hbaseline h.1 h.2
    have htriv : WorldwiseTrivialProfile train1 train2 := by
      apply firstParagraph_worldwise_train_trivial alpha beta reward cost
        (fun w => (p w).jointTT) train1 train2 hbase hforms
      · intro w
        simpa [hcommonAlpha w, hcommonBeta w] using hnash w
      · exact hjoint
    intro w q htrade
    have hfalse : TrainSharing.Theorem43.tradeEvent (train1 w) (train2 w) q = false := by
      simp [TrainSharing.Theorem43.tradeEvent, (htriv w).1 q.1, (htriv w).2 q.2]
    exact (Bool.false_ne_true (hfalse ▸ htrade)).elim
  · exact (hfollowInactiveImpossible h.1 h.2).elim
  · exact hfollowFollow h.1 h.2
  · intro w q _
    exact h q

end TrainSharing.Theorem46
