import RequestProject.TwoHypotheses

/-!
# Deriving the two-hypotheses observations and Theorem 5.2

This file closes two gaps left by the initial Section 5 formalization.

First, the infinite-data observations are derived from the conditional inference laws.  An
infinite sample identifies the joint marginal law of `(label, own signal)`.  Firm 1's two
marginals differ (and hence identify the hypothesis when `κ > 0`), while Firm 2's marginals
are equal.  Thus the observations used in `TwoHypothesesParameters.environment` are
posteriors generated by the basic model, rather than independent assumptions.

Second, the one-sample experiment of Section 5.2 is constructed by pushing a fresh labeled
inference draw to the two firms' labeled observations.  We formalize the learning event,
the posterior calculations used in Appendix D, all four displayed equilibrium-payoff
vectors, and the exact rational witness from the manuscript.  The final theorem is the
finite scalar equilibrium characterization of Theorem 5.2, parallel to `theorem5_1`.
-/

namespace TrainSharing
namespace TwoHypothesesParameters

/-- The population law of `(label, Firm 1 signal)` derived from the primitive inference law. -/
def primaryPopulationMarginal (x : TwoHypothesesParameters) (w : Hypothesis)
    (z : Bool × Bool) : ℝ :=
  ∑ s₂ : Bool, x.inferenceMass w (z.1, z.2, s₂)

/-- The population law of `(label, Firm 2 signal)` derived from the primitive inference law. -/
def secondaryPopulationMarginal (x : TwoHypothesesParameters) (w : Hypothesis)
    (z : Bool × Bool) : ℝ :=
  ∑ s₁ : Bool, x.inferenceMass w (z.1, s₁, z.2)

lemma primary_population_I_positive_true (x : TwoHypothesesParameters) :
    x.primaryPopulationMarginal .I (true, true) = x.k := by
  simp [primaryPopulationMarginal, inferenceMass]

lemma primary_population_II_positive_true (x : TwoHypothesesParameters) :
    x.primaryPopulationMarginal .II (true, true) = 0 := by
  simp [primaryPopulationMarginal, inferenceMass]

/-- With positive incidence, Firm 1's exact population marginal identifies the hypothesis. -/
theorem primary_population_identifies_hypothesis (x : TwoHypothesesParameters)
    (hk : 0 < x.k) : Function.Injective x.primaryPopulationMarginal := by
  intro w v h
  cases w <;> cases v
  · rfl
  · have := congrFun h (true, true)
    simp [primary_population_I_positive_true, primary_population_II_positive_true] at this
    linarith
  · have := congrFun h (true, true)
    simp [primary_population_I_positive_true, primary_population_II_positive_true] at this
    linarith
  · rfl

/-- Firm 2 has exactly the same population marginal under both hypotheses. -/
theorem secondary_population_uninformative (x : TwoHypothesesParameters) :
    x.secondaryPopulationMarginal .I = x.secondaryPopulationMarginal .II := by
  funext z
  fin_cases z <;> simp [secondaryPopulationMarginal, inferenceMass]

/-- The deterministic infinite-data observation encoded in the earlier environment is the
hypothesis recovered from Firm 1's derived population law. -/
theorem infinite_primary_observation_is_derived (x : TwoHypothesesParameters)
    (hk : 0 < x.k) (w v : Hypothesis) :
    x.primaryPopulationMarginal v = x.primaryPopulationMarginal w ↔ v = w := by
  constructor
  · intro h
    exact x.primary_population_identifies_hypothesis hk h
  · rintro rfl
    rfl

/-- Firm 2's `Unit` observation in the earlier environment is justified by equality of its
population laws, not posited as an additional informational assumption. -/
theorem infinite_secondary_observation_is_derived (x : TwoHypothesesParameters)
    (w v : Hypothesis) :
    x.secondaryPopulationMarginal v = x.secondaryPopulationMarginal w := by
  cases w <;> cases v
  · rfl
  · exact x.secondary_population_uninformative.symm
  · exact x.secondary_population_uninformative
  · rfl

/-- One firm's labeled historical observation: `(own signal, label)`. -/
abbrev LabeledObservation := Bool × Bool

/-- Projection of one primitive inference realization to the pair of labeled observations. -/
def labeledProjection (o : InferenceOutcome) : LabeledObservation × LabeledObservation :=
  ((o.2.1, o.1), (o.2.2, o.1))

/-- The one-sample joint training law, derived by pushforward from `inferenceMass`. -/
def oneSampleTrainingMass (x : TwoHypothesesParameters) (w : Hypothesis)
    (z : LabeledObservation × LabeledObservation) : ℝ :=
  if z.1.2 = z.2.2 then x.inferenceMass w (z.1.2, z.1.1, z.2.1) else 0

lemma oneSampleTrainingMass_nonneg (x : TwoHypothesesParameters) (hx : x.Feasible)
    (w z) : 0 ≤ x.oneSampleTrainingMass w z := by
  simp only [oneSampleTrainingMass]
  split
  · exact x.inferenceMass_nonneg hx w _
  · exact le_rfl

lemma oneSampleTrainingMass_total (x : TwoHypothesesParameters) (w) :
    ∑ z, x.oneSampleTrainingMass w z = 1 := by
  cases w <;>
    simp_rw [Fintype.sum_prod_type, Fintype.sum_bool] <;>
    simp [oneSampleTrainingMass, inferenceMass] <;> ring

/-- The one-sample experiment as an instance of the general signaling model. -/
def oneSampleEnvironment (x : TwoHypothesesParameters) (hx : x.Feasible) :
    BayesianEnvironment Hypothesis LabeledObservation LabeledObservation where
  prior := x.hypothesisLaw hx
  training w := {
    mass := x.oneSampleTrainingMass w
    nonneg := x.oneSampleTrainingMass_nonneg hx w
    total := x.oneSampleTrainingMass_total w }
  inference := x.inferenceLaw hx

/-- A complete labeled sample reveals the hypothesis exactly in the cases described in
Appendix D: `Aa` or `Ba`; equivalently the two historical signals have second signal `a`. -/
def jointSampleReveals (z : LabeledObservation × LabeledObservation) : Bool := z.2.1

/-- Probability that a shared single sample reveals the hypothesis. -/
def oneSampleLearningProbability (x : TwoHypothesesParameters) : ℝ :=
  x.k + (1 - x.k) * x.m

lemma joint_sample_reveals_probability (x : TwoHypothesesParameters) (w : Hypothesis) :
    (∑ z, if jointSampleReveals z = true then x.oneSampleTrainingMass w z else 0) =
      x.oneSampleLearningProbability := by
  cases w <;> simp_rw [Fintype.sum_prod_type, Fintype.sum_bool] <;>
    simp [oneSampleTrainingMass, jointSampleReveals,
      oneSampleLearningProbability, inferenceMass]
  all_goals ring

/-- The two hypotheses give the same mass to every nonrevealing complete sample. -/
lemma nonrevealing_joint_sample_same_mass (x : TwoHypothesesParameters)
    (z : LabeledObservation × LabeledObservation) (hz : jointSampleReveals z = false) :
    x.oneSampleTrainingMass .I z = x.oneSampleTrainingMass .II z := by
  fin_cases z <;> simp_all [jointSampleReveals, oneSampleTrainingMass, inferenceMass]

/-- A revealing complete sample has support in at most one hypothesis. -/
lemma revealing_joint_sample_separates (x : TwoHypothesesParameters)
    (z : LabeledObservation × LabeledObservation) (hz : jointSampleReveals z = true) :
    x.oneSampleTrainingMass .I z = 0 ∨ x.oneSampleTrainingMass .II z = 0 := by
  fin_cases z <;> simp_all [jointSampleReveals, oneSampleTrainingMass, inferenceMass]

/-- Firm 2's *individual* one-sample observation has equal likelihood under I and II. -/
lemma secondary_one_sample_likelihood_equal (x : TwoHypothesesParameters)
    (t₂ : LabeledObservation) :
    ∑ t₁, x.oneSampleTrainingMass .I (t₁, t₂) =
      ∑ t₁, x.oneSampleTrainingMass .II (t₁, t₂) := by
  fin_cases t₂ <;>
    simp_rw [Fintype.sum_prod_type, Fintype.sum_bool] <;>
    simp [oneSampleTrainingMass, inferenceMass]

/-- Consequently Firm 2's one-sample posterior remains its prior whenever the observation
has positive mass. -/
theorem secondary_one_sample_posterior_eq_prior (x : TwoHypothesesParameters)
    (hx : x.Feasible) (t₂ : LabeledObservation)
    (hpos : 0 < (x.oneSampleEnvironment hx).trainingMass .firm2 t₂) :
    (x.oneSampleEnvironment hx).posteriorWorld .firm2 t₂ .I = x.p := by
  have heq := x.secondary_one_sample_likelihood_equal t₂
  let L := ∑ t₁, x.oneSampleTrainingMass .II (t₁, t₂)
  have hmass : (x.oneSampleEnvironment hx).trainingMass .firm2 t₂ = L := by
    simp only [BayesianEnvironment.trainingMass, oneSampleEnvironment, hypothesisLaw]
    rw [show (Finset.univ : Finset Hypothesis) = {.I, .II} by decide]
    simp [hypothesisMass]
    rw [heq]
    dsimp [L]
    ring
  have hL : L ≠ 0 := by rw [hmass] at hpos; exact ne_of_gt hpos
  simp only [BayesianEnvironment.posteriorWorld]
  rw [hmass]
  change (x.p * (∑ t₁, x.oneSampleTrainingMass .I (t₁, t₂))) / L = x.p
  rw [heq]
  change (x.p * L) / L = x.p
  exact mul_div_cancel_right₀ x.p hL

/-- Appendix-D posterior after Firm 1 sees historical `(A,0)`. -/
noncomputable def posteriorAfterA0 (x : TwoHypothesesParameters) : ℝ :=
  x.l * x.p / (x.l * x.p + (1 - x.p) * (x.l + x.m))

/-- Appendix-D posterior after Firm 1 sees historical `(B,0)`. -/
noncomputable def posteriorAfterB0 (x : TwoHypothesesParameters) : ℝ :=
  (1 - x.l) * x.p /
    ((1 - x.l) * x.p + (1 - x.p) * (1 - x.l - x.m))

lemma primary_A0_likelihood_I (x : TwoHypothesesParameters) :
    ∑ t₂, x.oneSampleTrainingMass .I ((true, false), t₂) = (1 - x.k) * x.l := by
  simp_rw [Fintype.sum_prod_type, Fintype.sum_bool]
  simp [oneSampleTrainingMass, inferenceMass]

lemma primary_A0_likelihood_II (x : TwoHypothesesParameters) :
    ∑ t₂, x.oneSampleTrainingMass .II ((true, false), t₂) =
      (1 - x.k) * (x.l + x.m) := by
  simp_rw [Fintype.sum_prod_type, Fintype.sum_bool]
  simp [oneSampleTrainingMass, inferenceMass]
  ring

lemma primary_B0_likelihood_I (x : TwoHypothesesParameters) :
    ∑ t₂, x.oneSampleTrainingMass .I ((false, false), t₂) =
      (1 - x.k) * (1 - x.l) := by
  simp_rw [Fintype.sum_prod_type, Fintype.sum_bool]
  simp [oneSampleTrainingMass, inferenceMass]
  ring

lemma primary_B0_likelihood_II (x : TwoHypothesesParameters) :
    ∑ t₂, x.oneSampleTrainingMass .II ((false, false), t₂) =
      (1 - x.k) * (1 - x.l - x.m) := by
  simp_rw [Fintype.sum_prod_type, Fintype.sum_bool]
  simp [oneSampleTrainingMass, inferenceMass]

/-- The action-selection inequalities explicitly imposed in the manuscript's proof. -/
def OneSampleActionConditions (x : TwoHypothesesParameters) : Prop :=
  let wA := x.posteriorAfterA0
  let wB := x.posteriorAfterB0
  wA * (1 - x.k) * x.l / 2 + (1 - wA) * (1 - x.k) * (x.l + x.m) / 2 >
      wA * x.k ∧
  wA * (1 - x.k) * (1 - x.l) / 2 +
      (1 - wA) * (1 - x.k) * (1 - x.l - x.m) / 2 > (1 - wA) * x.k ∧
  wB * (1 - x.k) * x.l / 2 + (1 - wB) * (1 - x.k) * (x.l + x.m) / 2 >
      wB * x.k ∧
  wB * (1 - x.k) * (1 - x.l) / 2 +
      (1 - wB) * (1 - x.k) * (1 - x.l - x.m) / 2 > (1 - wB) * x.k ∧
  x.p * (1 - x.k) * x.m < (1 - x.p) * x.k / 2 ∧
  (1 - x.p) * (1 - x.k) * x.m / 2 > x.p * x.k ∧
  wB * (1 - x.k) * x.m > (1 - wB) * x.k / 2 ∧
  wB * x.k < (1 - wB) * (1 - x.k) * x.m / 2

/-- No-sharing equilibrium payoff from Appendix D (one sample). -/
noncomputable def oneSampleNoPayoff (x : TwoHypothesesParameters) : Firm → ℝ
  | .firm1 => x.p * (x.k * (x.k + (1 - x.k) * (1 - x.l) / 2) +
      (1 - x.k) * (1 - x.k) / 2) + (1 - x.p) * (1 - x.k) / 2
  | .firm2 => x.p * (x.k * ((1 - x.k) * x.l + (1 - x.k) * (1 - x.l) / 2) +
      (1 - x.k) * (1 - x.k) / 2) + (1 - x.p) * (1 - x.k) / 2

/-- Train-sharing equilibrium payoff from Appendix D (one sample). -/
noncomputable def oneSampleTrainPayoff (x : TwoHypothesesParameters) : Firm → ℝ
  | .firm1 => x.p * (x.oneSampleLearningProbability * (x.k + (1 - x.k) / 2) +
      (1 - x.oneSampleLearningProbability) * (1 - x.k) / 2) +
      (1 - x.p) * (1 - x.k) / 2
  | .firm2 => x.p * (x.oneSampleLearningProbability *
      ((1 - x.k) * x.l + (1 - x.k) * (1 - x.l) / 2) +
      (1 - x.oneSampleLearningProbability) * (1 - x.k) / 2) +
      (1 - x.p) * (1 - x.k) / 2

/-- Infer-sharing equilibrium payoff from Appendix D (one sample). -/
noncomputable def oneSampleInferPayoff (x : TwoHypothesesParameters) : Firm → ℝ
  | .firm1 => x.p * (x.k * (x.k + (1 - x.k) / 2) + (1 - x.k)^2 / 2) +
      (1 - x.p) * ((1 - x.k)^2 * (1 - x.l - x.m) / 2 +
        (x.k + (1 - x.k) * (x.l + x.m)) / 2)
  | .firm2 => x.p * (1 - x.k) / 2 +
      (1 - x.p) * ((1 - x.k)^2 * (1 - x.l - x.m) / 2 +
        ((1 - x.k) * (x.l + x.m) + x.k) / 2)

/-- Accuracy when the shared sample did not reveal the hypothesis. -/
def oneSamplePriorAccuracy (x : TwoHypothesesParameters) : ℝ :=
  x.p * (1 - x.k) * (1 - x.m) + (1 - x.p)

/-- Full-sharing equilibrium payoff from Appendix D (one sample). -/
noncomputable def oneSampleFullPayoff (x : TwoHypothesesParameters) (_i : Firm) : ℝ :=
  (x.oneSampleLearningProbability +
    (1 - x.oneSampleLearningProbability) * x.oneSamplePriorAccuracy) / 2

noncomputable def oneSampleReducedPayoff (x : TwoHypothesesParameters) : Contract → Firm → ℝ
  | .noSharing => x.oneSampleNoPayoff
  | .trainSharing => x.oneSampleTrainPayoff
  | .inferSharing => x.oneSampleInferPayoff
  | .fullSharing => x.oneSampleFullPayoff

/-- Ex-ante IR in the Appendix-D equilibrium characterization. -/
def OneSampleReducedIR (x : TwoHypothesesParameters) (c : Contract) : Prop :=
  ∀ i, x.oneSampleNoPayoff i ≤ x.oneSampleReducedPayoff c i

/-- Pareto optimality among ex-ante-IR contracts in the displayed equilibrium profile. -/
def OneSampleReducedStrictlyDominates (x : TwoHypothesesParameters)
    (c d : Contract) : Prop :=
  (∀ i, x.oneSampleReducedPayoff d i ≤ x.oneSampleReducedPayoff c i) ∧
  (∃ i, x.oneSampleReducedPayoff d i < x.oneSampleReducedPayoff c i)

/-- Pareto optimality among ex-ante-IR contracts in the displayed equilibrium profile. -/
def OneSampleReducedIRPO (x : TwoHypothesesParameters) (c : Contract) : Prop :=
  x.OneSampleReducedIR c ∧ ∀ d, x.OneSampleReducedIR d →
    ¬ x.OneSampleReducedStrictlyDominates d c

/-- The exact witness printed at the end of the proof of Theorem 5.2. -/
noncomputable def theorem52Witness : TwoHypothesesParameters where
  incidence := 201 / 2048
  mutationNoise := 1 / 64
  environmentNoise := 29 / 64
  priorI := 1 / 16

lemma theorem52Witness_in_51_box : theorem52Witness.InTheorem51Box := by
  norm_num [theorem52Witness, InTheorem51Box]

lemma theorem52Witness_structural : theorem52Witness.StructuralConditions := by
  norm_num [theorem52Witness, StructuralConditions]

/-- The manuscript's witness satisfies the corrected nonempty region used by the formal
version of Theorem 5.1, not merely its printed rectangular box. -/
lemma theorem52Witness_in_51_region : theorem52Witness.InTheorem51Region := by
  refine ⟨theorem52Witness_in_51_box, theorem52Witness_structural, ?_, ?_⟩
  · exact theorem51Box_inferActions theorem52Witness theorem52Witness_in_51_box
  · exact theorem51Box_inferStrictlyImproves theorem52Witness theorem52Witness_in_51_box

lemma theorem52Witness_actions : theorem52Witness.OneSampleActionConditions := by
  norm_num [theorem52Witness, OneSampleActionConditions, posteriorAfterA0, posteriorAfterB0]

lemma theorem52Witness_full_strictly_dominates (c : Contract)
    (hc : c ≠ .fullSharing) :
    ∀ i, theorem52Witness.oneSampleReducedPayoff c i <
      theorem52Witness.oneSampleReducedPayoff .fullSharing i := by
  intro i
  cases c <;> cases i <;>
    norm_num [theorem52Witness, oneSampleReducedPayoff, oneSampleNoPayoff,
      oneSampleTrainPayoff, oneSampleInferPayoff, oneSampleFullPayoff,
      oneSampleLearningProbability, oneSamplePriorAccuracy]
  all_goals exact (hc rfl).elim

lemma theorem52Witness_all_contracts_IR (c : Contract) :
    theorem52Witness.OneSampleReducedIR c := by
  intro i
  cases c <;> cases i <;>
    norm_num [theorem52Witness, OneSampleReducedIR, oneSampleReducedPayoff,
      oneSampleNoPayoff, oneSampleTrainPayoff, oneSampleInferPayoff,
      oneSampleFullPayoff, oneSampleLearningProbability, oneSamplePriorAccuracy]

/-- Theorem 5.2, at the manuscript's exact witness: it lies in the parameter range of
Theorem 5.1; no- and train-sharing have different equilibrium payoff vectors; and
full-sharing is the unique IRPO contract in the one-sample equilibrium characterization. -/
theorem theorem5_2 :
    theorem52Witness.InTheorem51Region ∧
    theorem52Witness.OneSampleActionConditions ∧
    theorem52Witness.oneSampleNoPayoff ≠ theorem52Witness.oneSampleTrainPayoff ∧
    theorem52Witness.OneSampleReducedIRPO .fullSharing ∧
    ∀ c, theorem52Witness.OneSampleReducedIRPO c → c = .fullSharing := by
  refine ⟨theorem52Witness_in_51_region, theorem52Witness_actions, ?_, ?_, ?_⟩
  · intro h
    have := congrFun h Firm.firm1
    norm_num [theorem52Witness, oneSampleNoPayoff, oneSampleTrainPayoff,
      oneSampleLearningProbability] at this
  · constructor
    · exact theorem52Witness_all_contracts_IR .fullSharing
    · intro d hd hdom
      by_cases h : d = .fullSharing
      · subst d
        rcases hdom.2 with ⟨i, hi⟩
        cases i <;> simp at hi
      · obtain ⟨i, hi⟩ := hdom.2
        have hlt := theorem52Witness_full_strictly_dominates d h i
        -- `d` cannot dominate a contract which is strictly better for both firms.
        exact (not_lt_of_ge (hdom.1 i)) hlt
  · intro c hc
    by_contra h
    have hfullIR := theorem52Witness_all_contracts_IR .fullSharing
    apply hc.2 .fullSharing hfullIR
    constructor
    · intro i
      exact le_of_lt (theorem52Witness_full_strictly_dominates c h i)
    · exact ⟨.firm1, theorem52Witness_full_strictly_dominates c h .firm1⟩

end TwoHypothesesParameters
end TrainSharing
